"""add expires_at to notifications

Revision ID: 74774ff4894c
Revises: 5e881b866e9e
Create Date: 2025-06-25 21:22:40.109434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74774ff4894c'
down_revision = '5e881b866e9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expires_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_column('expires_at')

    # ### end Alembic commands ###
