"""Add reset_token and reset_token_expires_at to User

Revision ID: 9c80566329ad
Revises: 5d43da32ca2c
Create Date: 2025-06-29 00:13:15.138961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c80566329ad'
down_revision = '5d43da32ca2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_token', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('reset_token_expires_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('reset_token_expires_at')
        batch_op.drop_column('reset_token')

    # ### end Alembic commands ###
